### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by jhillacre** [theY4Kman/dcrf-client#10]
I was looking at making a pull request with a feature I'd like to see in dcrf-client. I started by looking at following the development section from the readme to get tests running. I am running into some minor issues I was able to deal with and one last issue I'm not sure how to work around :

- The readme states to start with `pipenv install`. `pipenv` does not install dev packages by default, which seem to be required to run tests. This could be addressed by directing contributors to `pipenv install --dev`. Not sure what use `dev-packages` are in the context of dcrf-client, is it seperated for example reasons?
- Running `npm run test` next as in the readme doesn't work because py.test is not in the path yet. `pipenv shell` needs to be run first or instead run `pipenv run npm run test`.
- Running `npm run test` in a pipenv shell for python 3.7 doesn't work with a traceback of
  ```
  > dcrf-client@0.3.0 test:integration /home/joel/WebstormProjects/dcrf-client
  > py.test || true

  Traceback (most recent call last):
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/bin/py.test", line 5, in <module>
      from pytest import console_main
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pytest/__init__.py", line 3, in   <module>
      from . import collect
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pytest/collect.py", line 8, in   <module>
      from _pytest.deprecated import PYTEST_COLLECT_MODULE
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/deprecated.py", line 11,   in <module>
      from _pytest.warning_types import PytestDeprecationWarning
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/warning_types.py", line 7, in <module>
      from _pytest.compat import final
    File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/compat.py", line 57, in   <module>
      import importlib_metadata  # noqa: F401
  ModuleNotFoundError: No module named 'importlib_metadata'
  ```
  
  This seems related to this pytest issue: https://github.com/pytest-dev/pytest/issues/7114. The resolution seems to be to regenerate the `Pipfile.lock` per: https://github.com/pytest-dev/pytest/issues/7114#issuecomment-641822774. I did this using `pipenv lock; pipenv install --dev`.
- At this point, the unit tests now run for me, but there is an issue I'm not familiar with running the integration tests. Is it possible a `pytest` version that is too new is specified in the `Pipfile.lock` file?
  ```
  (dcrf-client-CumnqgWw) [joel@adamant dcrf-client]$ npm run test:integration
  > > dcrf-client@0.3.0 test:integration /home/joel/WebstormProjects/dcrf-client
  > py.test || true

  =================================================================================== test session starts ====================================================================================
  platform linux -- Python 3.7.9, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/bin/python3
  cachedir: .pytest_cache
  django: settings: dcrf_client_test.settings (from ini)
  rootdir: /home/joel/WebstormProjects/dcrf-client, configfile: pytest.ini
  plugins: django-4.1.0, pythonpath-0.7.3
  collecting ... Using selector: EpollSelector
  Expecting event from Mocha of type(s): collect
  Read event from Mocha: {'type': 'collect', 'tests': [{'title': 'returns created values', 'parents': ['DCRFClient', 'things', 'create', 'returns created values'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'imbues retrieve with data', 'parents': ['DCRFClient', 'things', 'create', 'imbues retrieve with data'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns empty set', 'parents': ['DCRFClient', 'things', 'list', 'returns empty set'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created rows', 'parents': ['DCRFClient', 'things', 'list', 'returns created rows'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on change', 'parents': ['DCRFClient', 'things', 'subscribe', 'invokes callback on change'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on delete', 'parents': ['DCRFClient', 'things', 'subscribe', 'invokes callback on delete'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created values', 'parents': ['DCRFClient', 'things_with_id', 'create', 'returns created values'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'imbues retrieve with data', 'parents': ['DCRFClient', 'things_with_id', 'create', 'imbues retrieve with data'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns empty set', 'parents': ['DCRFClient', 'things_with_id', 'list', 'returns empty set'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'returns created rows', 'parents': ['DCRFClient', 'things_with_id', 'list', 'returns created rows'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on change', 'parents': ['DCRFClient', 'things_with_id', 'subscribe', 'invokes callback on change'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}, {'title': 'invokes callback on delete', 'parents': ['DCRFClient', 'things_with_id', 'subscribe', 'invokes callback on delete'], 'file': '/home/joel/WebstormProjects/dcrf-client/test/integration/tests/test.ts'}]}
  INTERNALERROR> Traceback (most recent call last):
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
  INTERNALERROR>     config.hook.pytest_collection(session=session)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
  INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
  INTERNALERROR>     return outcome.get_result()
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
  INTERNALERROR>     res = hook_impl.function(*args)
  INTERNALERROR>   File "/home/joel/WebstormProjects/dcrf-client/test/integration/tests/mocha.py", line 179, in pytest_collection
  INTERNALERROR>     session=session,
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/nodes.py", line 91, in __call__
  INTERNALERROR>     fail(msg, pytrace=False)
  INTERNALERROR>   File "/home/joel/.local/share/virtualenvs/dcrf-client-CumnqgWw/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
  INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
  INTERNALERROR> Failed: Direct construction of MochaFile has been deprecated, please use MochaFile.from_parent.
  INTERNALERROR> See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

  ================================================================================== no tests ran in 0.00s ===================================================================================
  sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=15>
  sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=16>
  (dcrf-client-CumnqgWw) [joel@adamant dcrf-client]$
  ```

**Comment by jhillacre** [comment]
I realized the last output I pasted says `pytest-6.2.1`, because pipenv install will update depenances if not capped in the `Pipfile`. Using `pipenv install --dev --keep-outdated "importlib-metadata"` instead to fix the import issue, keeps `pytest-6.1.2`  as in the published `Piplock.file`. The integration tests still output the same error as above with that version.

**Comment by theY4Kman** [comment]
Ooof, I'm so sorry for this less-than-ideal experience.

 - > The readme states to start with `pipenv install`

 	Hmm, using dev dependencies was force of habit. There _may_ be some value in separating them for purpose of example, but you're absolutely right: the instructions should be for `pipenv install --dev`

 - > Running `npm run test` next as in the readme doesn't work because py.test is not in the path yet

	Ouch, yeah, I'm so used to creating a virtualenv manually – foregoing pipenv's creation of one – such that `py.test` is always on the PATH. But this is not a friendly assumption to make. The `package.json` must be changed to use `pipenv run py.test` for the `test:integration` script.

 - > Running `npm run test` in a pipenv shell for python 3.7 doesn't work
   > Is it possible a pytest version that is too new is specified in the Pipfile.lock file?

	Hmm, the deps are likely wildly out of date, and could use an update. I'm aware of the pytest change that would cause `Direct construction of MochaFile has been deprecated, please use MochaFile.from_parent`; I shall update the pytest plugin to fix that.

	I've made a bunch of changes to the test runner (as well as a few changes to the client, at least with respect to logging – switched to winston), and I _may_ have already fixed this. Regardless, I'll get it squared away.


Beyond addressing what you've mentioned here, I think it would be wise if I added a `Dockerfile` capable of running the tests, so at the very least the suite may be run without having to perform any potentially hairy setup.

Again, sorry for this shit experience, but thank you for submitting this report. These changes will improve the experience for everyone, and I really appreciate the opportunity to better the project :)


## TODO
Some action items for myself, so I don't forget

 - [ ] Change pipenv installation instructions to `pipenv install --dev`
 - [ ] Change `test:integration` command to `pipenv run py.test` (to run within virtualenv)
 - [ ] Update Pipfile deps
 - [ ] Ensure `MochaFile.from_parent` is used in custom collector w/ newer versions of pytest
 - [ ] Create `Dockerfile` for running test suite
